### ISSUE TITLE
Could you include some datasets for users to play with the tool?

### ISSUE THREAD

**Issue by zpeng2003bht** [fonsecag/FFAST#1]
Hi:

Thanks for the nice paper "Force Field Analysis Software and Tools (FFAST): Assessing Machine Learning
Force Fields Under the Microscope" (arXiv:2308.06871v1) and the Python tool for FF quality assessment. 

Could you please include a few sample datasets so that users can play with the downloaded FFAST tool immediately? 
The datasets featured inside the paper would be nice. 

best,
Zhengwei Peng

**Comment by fonsecag** [comment]
Hey.

The pre-computed predictions used in the original paper are now included in the examples/ folder. The corresponding datasets (Docosahexaenoic acid and Stachyose) will still have to be downloaded from the original source (http://www.sgdml.org/#datasets) though. 

I have added a small session to the current README to explain how to load the example datasets and models to immediately jump into playing with the tools.

Thank you for the suggestion!
